#!/bin/bash
# Quick commands cho Thach Vu Land workflow

echo "📋 THACH VU LAND - QUICK COMMANDS"
echo "================================="
echo ""
echo "1️⃣  Setup Sheet Structure (first time only)"
echo "   cd /Users/admin/automation/scripts/drive-uploader"
echo "   node setup-thachvuland-sheet.js"
echo ""
echo "2️⃣  Test Integration"
echo "   node test-thachvuland-integration.js"
echo ""
echo "3️⃣  Check Sheet Status"
echo "   node check-thachvuland-sheet.js"
echo ""
echo "4️⃣  Generate Content"
echo "   cd /Users/admin/automation"
echo "   npm run daily -- thachvuland"
echo ""
echo "5️⃣  Upload to Drive + Auto-sync to Sheet"
echo "   cd scripts/drive-uploader"
echo "   npm run upload:tvland"
echo ""
echo "6️⃣  Open Google Sheet in Browser"
echo "   open 'https://docs.google.com/spreadsheets/d/1SNv1t0h-KRXWQ4xANroW5RQN6zHU57OrrXj_OqzfVsY'"
echo ""
echo "7️⃣  View n8n Workflow"
echo "   open 'https://n8n.yourdomain.com/workflow/autopost-tvland'"
echo ""
echo "================================="
echo "✅ Sheet is optimized for n8n workflow!"
echo ""
