#!/bin/bash

# Quick commands cho Thach Vu Land với thông tin liên hệ mới

echo "📞 THACH VU LAND - THÔNG TIN LIÊN HỆ"
echo "====================================="
echo ""
echo "📞 Hotline: 0903.469.888"
echo "📍 Địa chỉ: 32 đường 40 . KDC Vạn Phúc , TP Thủ Đức"
echo "💬 Zalo: 0903.469.888"
echo "🌐 Website: thachvuland.com"
echo ""
echo "====================================="
echo ""
echo "🚀 QUICK COMMANDS:"
echo ""
echo "1️⃣  Xem thông tin liên hệ"
echo "   cd /Users/admin/automation/brands/thachvuland"
echo "   node caption-helper.js --contact-only"
echo ""
echo "2️⃣  Tạo content mới (với contact info)"
echo "   cd /Users/admin/automation/scripts"
echo "   node test-thachvuland-with-contact.js"
echo ""
echo "3️⃣  Generate ảnh"
echo "   cd /Users/admin/automation"
echo "   node scripts/carousel-generator/generator.js carousel-generator/content/[filename].json"
echo ""
echo "4️⃣  Upload và sync to Sheet"
echo "   cd /Users/admin/automation/scripts/drive-uploader"
echo "   node upload-thachvuland.js [folder-name]"
echo ""
echo "5️⃣  Update caption cũ"
echo "   cd /Users/admin/automation/brands/thachvuland"
echo "   node caption-helper.js \"Your old caption\""
echo ""
echo "====================================="
echo "✅ Thông tin liên hệ tự động thêm vào mọi post!"
echo ""
